name:                filehistogram
version:             0.1.0.0
github:              "githubuser/filehistogram"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/filehistogram#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 2.2.3.0
- containers >= 0.6.8
- directory >= 1.3.8.5
- filepath >= 1.4.301.0
- hvega >= 0.12.0.7
- process >= 1.6.25.0
- streamly >= 0.10.1
- streamly-core >= 0.2.3
- text >= 2.1.1
- time >= 1.12.2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
# realy needed?
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src

executables:
  filehistogram-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filehistogram

tests:
  filehistogram-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filehistogram
    - hspec
